# Generated by Django 5.2.7 on 2025-10-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_carbs_menuitem_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macrotracker',
            old_name='fats_consumed',
            new_name='fat_consumed',
        ),
    ]
