# core/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# R: I used Django REST Framework's DefaultRouter for the RestaurantViewSet.
# This is a  feature because it automatically generates the URLs
# for the list view (`/restaurants/`) and the detail view (`/restaurants/1/`).router = DefaultRouter()
router = DefaultRouter()
router.register(r'restaurants', views.RestaurantViewSet, basename='restaurant')

# The API URLs are now determined automatically by the router.
# We still need to manually add the paths for our function-based views.
urlpatterns = [
    # This includes the URLs automatically generated by the router.
    path('', include(router.urls)),
    
    # User management endpoints
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),

    # Core logic endpoints for the tracker
    path('tracker/', views.get_daily_tracker, name='get-daily-tracker'),
    path('log-meal/', views.log_meal, name='log-meal'),

    # R: (FUTURE PLAN) If I add a view to update a user's profile,
    # I would add its path here, like: path('profile/update/', ...),
]